### ISSUE TITLE
GNU 14.1.1 reguards the constexpr string formating magic as an error, works on GNU 13.2.1

### ISSUE THREAD

**Issue by odinthenerd** [dominicpoeschko/string_constant#2]
https://github.com/dominicpoeschko/string_constant/blob/eaed530a480480c666eba921afc4013976d1642e/src/string_constant/string_constant.hpp#L87

```
In file included from /project/kvasir/uc_log/remote_fmt/src/remote_fmt/remote_fmt.hpp:19:
/project/kvasir/uc_log/remote_fmt/string_constant/src/string_constant/string_constant.hpp:87:30: error: non-type template argument is not a constant expression
   87 |             std::array<char, []() { return StringGenerator{}().size(); }()> local_storage;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/project/kvasir/uc_log/remote_fmt/string_constant/src/string_constant/string_constant.hpp:86:44: note: while substituting into a lambda expression here
   86 |         static constexpr auto storage{[]() {
      |                                            ^
/project/kvasir/uc_log/remote_fmt/string_constant/src/string_constant/string_constant.hpp:104:20: note: in instantiation of template class 'sc::detail::FromStringGenerator<(lambda at /project/kvasir/uc_log/remote_fmt/string_constant/src/string_constant/string_constant.hpp:202:36)>' requested here
  104 |     return detail::FromStringGenerator<StringGenerator>::sc();
      |                    ^
/project/kvasir/uc_log/remote_fmt/string_constant/src/string_constant/string_constant.hpp:211:16: note: in instantiation of function template specialization 'sc::create<(lambda at /project/kvasir/uc_log/remote_fmt/string_constant/src/string_constant/string_constant.hpp:202:36)>' requested here
  211 |         return create(Generator);
      |                ^
/project/kvasir/cmake/../../chip/src/chip/I2C.hpp:429:21: note: in instantiation of function template specialization 'sc::detail::format<429U, (unsigned char)'\x05', '{', '}', ',', ' ', '{', '}'>' requested here
  429 |                     UC_LOG_C("abort send");
      |                     ^
/project/kvasir/uc_log/src/uc_log/uc_log.hpp:79:23: note: expanded from macro 'UC_LOG_C'
   79 | #define UC_LOG_C(...) UC_LOG(::uc_log::LogLevel::crit, __VA_ARGS__)
      |                       ^
/project/kvasir/uc_log/src/uc_log/uc_log.hpp:69:9: note: expanded from macro 'UC_LOG'
   69 |         UC_LOG_IMPL(level, __LINE__, __FILE_NAME__, fmt __VA_OPT__(, ) __VA_ARGS__)
      |         ^
/project/kvasir/uc_log/src/uc_log/uc_log.hpp:52:23: note: expanded from macro 'UC_LOG_IMPL'
   52 |                       format<static_cast<std::uint32_t>(line), static_cast<std::uint8_t>(level)>( \
      |                       ^
/project/docker_build/_deps/fmt-src/include/fmt/format.h:1287:10: note: cannot allocate array; evaluated array bound 1073741824 exceeds the limit (1048576); use '-fconstexpr-steps' to increase this limit
 1287 |   *out++ = static_cast<Char>('0' + value / 10);
 ```
